s = set()

n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))
n  = input("Enter a number: ")
s.add(int(n))

print("The set is: ", s)